version: '3.8'
networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - dev


  backend:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    networks:
      - dev
  
  db:
    image: postgres
    # restart: always # это поднимает контейнер каждый раз при запуске Docker Desktop
  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Craft123
      POSTGRES_DB: fast_api
    volumes:
    - pgdata1:/var/lib/postgresql/data   # монтируем том pgdata1 в /var/lib/postgresql/data для сохранения данных даже после docker compose down
    networks:
      - dev

volumes:  # указание глобального тома где-то в папках докера, чтобы не мозолила глаза
  pgdata1:

