"""password_hash

Revision ID: 0b875e19a6b9
Revises: be0ab2457fb9
Create Date: 2025-06-08 16:55:16.733555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b875e19a6b9"
down_revision: Union[str, None] = "be0ab2457fb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("mail", sa.String(), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default="now()", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("mail", name=op.f("uq_users_mail")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "info_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("foo", sa.Integer(), nullable=True),
        sa.Column("baz", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_info_users_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_info_users")),
        sa.UniqueConstraint("user_id", name=op.f("uq_info_users_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("info_users")
    op.drop_table("users")
    # ### end Alembic commands ###
