"""fix_created_at

Revision ID: 1aa4a39fc862
Revises: 80a9323e0955
Create Date: 2025-06-10 14:39:30.331841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1aa4a39fc862"
down_revision: Union[str, None] = "80a9323e0955"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-06-08 17:12:46.351823'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
